version: '3.1'
services:
  stats-server:
    build:
      context: statistics/stat-service
      dockerfile: Dockerfile
    container_name: stat-server-container
    restart: on-failure
    image: stat-image-explore
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
       - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
       - SPRING_DATASOURCE_USERNAME=explore
       - SPRING_DATASOURCE_PASSWORD=explore

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    restart: on-failure
    ports:
      - "6541:5432"
    environment:
    - POSTGRES_DB=stats-db
    - POSTGRES_PASSWORD=explore
    - POSTGRES_USER=explore
    volumes:
      - /var/lib/postgresql/data/

  ewm-service:
    build:
      context: main-service
      dockerfile: Dockerfile
    image: main-service-explore
    container_name: ewm-service
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explore
      - POSTGRES_PASSWORD=explore
      - POSTGRES_DB=explore

  ewm-db:
      image: postgres:14-alpine
      container_name: ewm-db
      restart: on-failure
      ports:
        - "6542:5432"
      volumes:
        - /var/lib/postgresql/data/
      environment:
        POSTGRES_PASSWORD: explore
        POSTGRES_USER: explore