version: '3.1'
services:
  stats-server:
    image: stat_service_image
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
       - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore
       - SPRING_DATASOURCE_USERNAME=explore
       - SPRING_DATASOURCE_PASSWORD=explore

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    restart: always
    ports:
      - "6546:5432"
    environment:
      POSTGRES_PASSWORD: explore
      POSTGRES_USER: explore
    volumes:
      - /var/lib/postgresql/data/

  ewm-service:
    image: main-service-explore
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explore-with-me-main
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
      - STATS_SERVICE_URL=http://stats-server:9090
      - JAVA_OPTS=-Djdk.httpclient.WebClient.log=errors,requests

  ewm-db:
      image: postgres:14-alpine
      container_name: ewm-db
      ports:
        - "6542:5432"
      volumes:
        - /var/lib/postgresql/data/
      environment:
        POSTGRES_PASSWORD: explore
        POSTGRES_USER: explore