version: '3.1'
services:
  stats-server:
    image: stat_service_image
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
       - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore
       - SPRING_DATASOURCE_USERNAME=explore
       - SPRING_DATASOURCE_PASSWORD=explore

  stats-db:
    image: postgres
    container_name: stats-db
    restart: always
    ports:
      - "6541:5432"
    environment:
      POSTGRES_PASSWORD: explore
      POSTGRES_USER: explore
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:

#  ewm-service:
#    ports:
#      - "8080:8080"

#  ewm-db:
#    image: postgres:14-alpine
